In [1]:
import pandas as pd
import numpy as np

In [2]:
np.random.seed(99)

n_samples = 1000
n_class_0 = 800
n_class_1 = 200

In [3]:
n_class_0, n_class_1

(800, 200)

In [5]:
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [6]:
class_0.shape, class_1.shape

((800, 3), (200, 3))

In [7]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [8]:
df.head()

   feature_1  feature_2  target
0  -0.142359  -0.761761       0
1   2.057222  -1.371581       0
2   0.283262  -0.314062       0
3   1.329812  -0.264179       0
4  -0.154622   1.173144       0

In [9]:
df.tail()

     feature_1  feature_2  target
995   0.056674   0.869481       1
996   2.965760   3.343386       1
997   2.726523   1.638403       1
998   1.951234   2.069752       1
999   2.372242   2.519511       1

In [10]:
df['target'].value_counts()

target
0    800
1    200
Name: count, dtype: int64

In [13]:
## upsampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [15]:
from sklearn.utils import resample
df_minority_unsampled = resample(df_minority, 
                        replace=True, n_samples=len(df_majority),
                        random_state=42
                        )

In [16]:
df_minority_upsampled.shape

(800, 3)

In [17]:
df_minority_upsampled.head()

     feature_1  feature_2  target
102   2.043006   2.201319       1
179   4.719251   1.953213       1
92    1.555764   2.952422       1
14    2.902212  -0.023447       1
106   1.933356   1.664673       1

In [18]:
df_upsampled=pd.concat([df_majority,df_minority_upsampled])

In [19]:
df_upsampled['target'].value_counts()

target
0    800
1    800
Name: count, dtype: int64

In [20]:
#downsampling

In [21]:
import pandas as pd

np.random.seed(123)

n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

df = pd.concat([class_0, class_1]).reset_index(drop=True)

print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [22]:
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [27]:
from sklearn.utils import resample
df_majority_unsampled = resample(df_majority, 
replace=True, n_samples=len(df_minority),
random_state=42
)

In [25]:
df_majority_unsampled.head()

     feature_1  feature_2  target
102   0.712265   0.718151       0
435   1.199988   0.574621       0
860   0.304515  -0.759475       0
270  -1.213385   0.675504       0
106   0.179549  -0.202659       0

In [28]:
df_upsampled1=pd.concat([df_majority_unsampled,df_minority])

In [29]:
df_upsampled1['target'].value_counts()

target
0    100
1    100
Name: count, dtype: int64